strata = {
	'LowerAlbedo' = {'/env/crystalline/layers/crystalwerk01_albedo.dds',6,}
	'LowerNormal' = {'/env/crystalline/layers/cr_04_01_normal.dds',15,}
	'Albedo0' = {'/env/crystalline/layers/cr_07_01b_albedo.dds',20,}
	'Normal0' = {'/env/crystalline/layers/cr_07_01b_normal.dds',20,}
	'Albedo1' = {'/env/crystalline/layers/crystalwerk04_b_albedo.dds',6,}
	'Normal1' = {'/env/crystalline/layers/cr_01_01_normal.dds',6,}
	'Albedo2' = {'/env/crystalline/layers/cr_sandwet_albedo.dds',3,}
	'Normal2' = {'/env/red barrens/layers/rb_cracked02_normal.dds',10,}
	'Albedo3' = {'/env/crystalline/layers/crystalwerk02b_albedo.dds',6,}
	'Normal3' = {'/env/crystalline/layers/crystalwerk02b_normal.dds',6,}
	'Albedo4' = {'/env/crystalline/layers/cr_rock05_albedo.dds',10,}
	'Normal4' = {'/env/crystalline/layers/cr_09_01_normal.dds',10,}
	'Albedo5' = {'/env/crystalline/layers/cr_rock002b_albedo.dds',8,}
	'Normal5' = {'/env/crystalline/layers/cr_rock002b_normal.dds',8,}
	'Albedo6' = {'/env/crystalline/layers/cryst_rock01_albedo.dds',7,}
	'Normal6' = {'/env/crystalline/layers/cryst_rock01_normal.dds',7,}
	'Albedo7' = {'/env/crystalline/layers/cr_rock001_albedo.dds',12,}
	'Normal7' = {'/env/crystalline/layers/cr_07_01b_normal.dds',8,}
	'UpperAlbedo' = {'/env/evergreen/layers/macrotexture000_albedo.dds',128,}
}
