version = 3
ScenarioInfo = {
    name = 'Adaptive Regor Highlands',
    description = 'Regor VI is a rocky planet located in the habitable zone of its host star Regor. While life can be found on Regor VI, and its colonization has been attempted, sustaining any non-indigenous life and thus a human population has proven to be impractical, due to the high portion of short waved radiation emitted by Regor VIs host star, a blue giant. The daylight is cold and glaring with a violet tint to it, straining the human eye. Today only a sparse population of former colonists remains. Contrary to its unsuitedness as a colony planet, it has been of some strategic interests during past conflicts and a handful of minor skirmishes have been fought over it. (MAP BY LIONHARDT, dynamic script and customizability by CookieNoob) [based on Version 1.5 (6)]',
    type = 'skirmish',
    starts = true,
    preview = '',
    map_version = 4,
    AdaptiveMap = true,
    size = {512, 512},
    map = '/maps/adaptive_regor_highlands.v0004/adaptive_regor_highlands.scmap',
    save = '/maps/adaptive_regor_highlands.v0004/adaptive_regor_highlands_save.lua',
    script = '/maps/adaptive_regor_highlands.v0004/adaptive_regor_highlands_script.lua',
    norushradius = 77.000000,
    norushoffsetX_ARMY_1 = 1.000000,
    norushoffsetY_ARMY_1 = 2.000000,
    norushoffsetX_ARMY_2 = -2.000000,
    norushoffsetY_ARMY_2 = -1.000000,
    norushoffsetX_ARMY_3 = -13.000000,
    norushoffsetY_ARMY_3 = 0.000000,
    norushoffsetX_ARMY_4 = 13.000000,
    norushoffsetY_ARMY_4 = 0.000000,
    norushoffsetX_ARMY_5 = 0.000000,
    norushoffsetY_ARMY_5 = 0.000000,
    norushoffsetX_ARMY_6 = 0.000000,
    norushoffsetY_ARMY_6 = 0.000000,
    norushoffsetX_ARMY_7 = 0.000000,
    norushoffsetY_ARMY_7 = 0.000000,
    norushoffsetX_ARMY_8 = 0.000000,
    norushoffsetY_ARMY_8 = 0.000000,
    norushoffsetX_ARMY_9 = 0.000000,
    norushoffsetY_ARMY_9 = 0.000000,
    norushoffsetX_ARMY_10 = 0.000000,
    norushoffsetY_ARMY_10 = 0.000000,
    norushoffsetX_ARMY_11 = 0.000000,
    norushoffsetY_ARMY_11 = 0.000000,
    norushoffsetX_ARMY_12 = 0.000000,
    norushoffsetY_ARMY_12 = 0.000000,
    Configurations = {
        ['standard'] = {
            teams = {
                { name = 'FFA', armies = {'ARMY_1','ARMY_2','ARMY_3','ARMY_4','ARMY_5','ARMY_6','ARMY_7','ARMY_8','ARMY_9','ARMY_10','ARMY_11','ARMY_12',} },
            },
            customprops = {
                ['ExtraArmies'] = STRING( 'ARMY_17 NEUTRAL_CIVILIAN' ),
            },
        },
    }}
